Traceback (most recent call last):
  File "/Users/tompinder/miniforge3/envs/gpjax/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/Users/tompinder/miniforge3/envs/gpjax/lib/python3.9/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Users/tompinder/miniforge3/envs/gpjax/lib/python3.9/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/Users/tompinder/miniforge3/envs/gpjax/lib/python3.9/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/Users/tompinder/miniforge3/envs/gpjax/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/Users/tompinder/miniforge3/envs/gpjax/lib/python3.9/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/Users/tompinder/miniforge3/envs/gpjax/lib/python3.9/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/Users/tompinder/miniforge3/envs/gpjax/lib/python3.9/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
vertex_per_side = 20
n_edges_to_remove = 30
p = 0.8

G = nx.barbell_graph(vertex_per_side, 0)

random.seed(123)
[G.remove_edge(*i) for i in random.sample(list(G.edges), n_edges_to_remove)]

pos = nx.spring_layout(G, seed=123)  # positions for all nodes

nx.draw(G)  # , pos, node_color="tab:blue", with_labels=False, alpha=0.5)
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mTypeError[0m                                 Traceback (most recent call last)
Cell [0;32mIn[2], line 12[0m
[1;32m      8[0m [G[38;5;241m.[39mremove_edge([38;5;241m*[39mi) [38;5;28;01mfor[39;00m i [38;5;129;01min[39;00m random[38;5;241m.[39msample([38;5;28mlist[39m(G[38;5;241m.[39medges), n_edges_to_remove)]
[1;32m     10[0m pos [38;5;241m=[39m nx[38;5;241m.[39mspring_layout(G, seed[38;5;241m=[39m[38;5;241m123[39m)  [38;5;66;03m# positions for all nodes[39;00m
[0;32m---> 12[0m [43mnx[49m[38;5;241;43m.[39;49m[43mdraw[49m[43m([49m[43mG[49m[43m)[49m  [38;5;66;03m# , pos, node_color="tab:blue", with_labels=False, alpha=0.5)[39;00m

File [0;32m~/.local/lib/python3.9/site-packages/networkx/drawing/nx_pylab.py:113[0m, in [0;36mdraw[0;34m(G, pos, ax, **kwds)[0m
[1;32m    111[0m cf[38;5;241m.[39mset_facecolor([38;5;124m"[39m[38;5;124mw[39m[38;5;124m"[39m)
[1;32m    112[0m [38;5;28;01mif[39;00m ax [38;5;129;01mis[39;00m [38;5;28;01mNone[39;00m:
[0;32m--> 113[0m     [38;5;28;01mif[39;00m [43mcf[49m[38;5;241;43m.[39;49m[43m_axstack[49m[43m([49m[43m)[49m [38;5;129;01mis[39;00m [38;5;28;01mNone[39;00m:
[1;32m    114[0m         ax [38;5;241m=[39m cf[38;5;241m.[39madd_axes(([38;5;241m0[39m, [38;5;241m0[39m, [38;5;241m1[39m, [38;5;241m1[39m))
[1;32m    115[0m     [38;5;28;01melse[39;00m:

[0;31mTypeError[0m: '_AxesStack' object is not callable
TypeError: '_AxesStack' object is not callable

